In [2]:
import numpy as np

In [3]:
L = [1,2,3]

In [7]:
A = np.array([1,2,3])

In [8]:
A = np.array([1,2,3])

In [9]:
print(A)

[1 2 3]


In [10]:
for e in L:
    print(e)

1
2
3


In [11]:
for e in A:
    print(e)

1
2
3


In [12]:
L.append("4")

In [13]:
print(L)

[1, 2, 3, '4']


In [14]:
# error
A.append(4)


SyntaxError: invalid syntax (<ipython-input-14-23ae7dfd7d84>, line 1)

In [15]:
L + [5]

[1, 2, 3, '4', 5]

In [19]:
# broadcasting illigal oprating in 
# maths cant add 2 vectors of dofferent sizes 
# but in numpy it makes sense
A + np.array([4])

array([5, 6, 7])

In [20]:
A + np.array([4,5,6])

array([5, 7, 9])

In [21]:
# error cant add vectors of diff. sizes
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
2 * A

array([2, 4, 6])

In [23]:
2 * L

[1, 2, 3, '4', 1, 2, 3, '4']

In [24]:
L + L

[1, 2, 3, '4', 1, 2, 3, '4']

In [25]:
A + A

array([2, 4, 6])

In [30]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [31]:
L.pop(3)

'4'

In [32]:
print(L)

[1, 2, 3]


In [33]:
L.append(4)

In [34]:
print(L)

[1, 2, 3, 4]


In [35]:
l2 = []
for e in L:
    l2.append(e+3)

In [36]:
print(l2)

[4, 5, 6, 7]


In [39]:
L2 = []
for e in L:
    L2.append(e**2)

In [40]:
L2

[1, 4, 9, 16]

In [41]:
A**2

array([1, 4, 9], dtype=int32)

In [42]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [43]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [44]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
#  trignometric
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])