In [1]:
import numpy as np

# creating an array of 0s
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
10 *  np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random()

0.7327281186383158

In [7]:
np.random.random((2,3))

array([[0.28447243, 0.21998876, 0.18055908],
       [0.47250901, 0.39282813, 0.77672104]])

In [9]:
# from normal distribution use "randn"
np.random.randn(2,3)

array([[ 1.42425434,  0.17535393,  2.32526355],
       [ 0.74268649, -0.68417245,  2.59621792]])

In [12]:
r = np.random.randn(1000)

In [23]:
r.mean()

0.05414505081467945

In [16]:
r.var()

0.9795685883189968

In [18]:
r.std()

0.9897315738719246

In [24]:
r= np.random.randn(1000, 3)

In [29]:
r.mean(axis = 0)  # calc mean of the 3 columns here

array([-0.01469838, -0.02202777,  0.05058988])

In [30]:
r.mean(axis = 1)  # calc mean of the 1000 rows here

array([-1.63352132e-01, -4.93170152e-01,  7.25802571e-01,  4.59771990e-01,
        8.11214270e-01, -6.01755287e-01, -6.27398825e-01, -8.24784317e-01,
       -2.42449253e-01,  5.00838825e-01, -8.63687949e-01,  6.91910074e-01,
       -6.59528810e-01, -1.14219894e-01,  2.53058040e-01,  3.09279215e-01,
       -2.04763595e-01, -2.11389577e-01,  1.89377849e-02, -1.81953565e-01,
       -3.24930376e-01, -7.60506485e-01, -9.66151885e-01, -7.51304237e-01,
        8.56991755e-01,  1.41016758e+00,  5.10483447e-01, -1.31991587e-01,
        8.32421131e-01,  9.28543421e-01,  1.14353079e+00, -4.73460847e-01,
       -4.64558115e-02,  6.85838581e-01, -3.44826371e-01, -4.26563321e-01,
        3.44351998e-01,  5.32432261e-01,  4.99838782e-01,  5.13961448e-01,
        2.40900942e-01, -1.28696435e+00,  1.14042466e+00,  7.74330884e-01,
       -4.18239412e-01,  3.73977646e-01, -2.61937848e-01, -3.22647936e-01,
        1.86433547e-01,  1.41594237e-01, -5.22160088e-01,  9.40878264e-01,
       -3.57676796e-01,  

In [31]:
r.mean(axis = 0).shape  

(3,)

In [32]:
r.mean(axis = 1).shape  

(1000,)

In [33]:
# covariance 
np.cov(r)

array([[ 0.34835599, -0.37721667,  0.08993239, ..., -0.19088949,
        -0.33896754, -0.53729747],
       [-0.37721667,  0.98060999, -1.04231796, ..., -0.0344949 ,
        -0.02057743, -0.15585905],
       [ 0.08993239, -1.04231796,  1.58384804, ...,  0.34907821,
         0.55268784,  1.07960858],
       ...,
       [-0.19088949, -0.0344949 ,  0.34907821, ...,  0.20628519,
         0.34915817,  0.605406  ],
       [-0.33896754, -0.02057743,  0.55268784, ...,  0.34915817,
         0.59245125,  1.02259124],
       [-0.53729747, -0.15585905,  1.07960858, ...,  0.605406  ,
         1.02259124,  1.7798069 ]])

In [34]:
np.cov(r).shape

(1000, 1000)

In [35]:
np.cov(r.T)

array([[ 1.05802456,  0.11766593, -0.00655659],
       [ 0.11766593,  1.01553966,  0.02094786],
       [-0.00655659,  0.02094786,  1.04363488]])

In [36]:
np.cov(r, rowvar=False)

array([[ 1.05802456,  0.11766593, -0.00655659],
       [ 0.11766593,  1.01553966,  0.02094786],
       [-0.00655659,  0.02094786,  1.04363488]])

In [38]:
np.random.randint(0,10, size=(3,3))  #random int from 0 to 10

array([[1, 6, 9],
       [1, 2, 4],
       [5, 7, 2]])

In [40]:
np.random.randint(10, size=(3,3)) #random int from 0 to 10

array([[8, 6, 3],
       [6, 8, 5],
       [6, 4, 7]])