In [6]:
import numpy as np
l = [[1,2],[3,4]]
l

[[1, 2], [3, 4]]

In [2]:
l[0]


[1, 2]

In [4]:
l[0][1]

2

In [9]:
a = np.array([[1,2],
             [3,4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
a[0][1]

2

In [11]:
a[0,1]

2

In [13]:
a[:,0]

array([1, 3])

In [14]:
a.T # transpose

array([[1, 3],
       [2, 4]])

In [15]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [17]:
np.exp(l)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [22]:
a.dot(b.T) #error

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [23]:
np.linalg.det(a)

-2.0000000000000004

In [24]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
np.linalg.inv(a).dot(a)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [26]:
np.trace(a)

5

In [27]:
np.diag(a)

array([1, 4])

In [30]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [31]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [32]:
Lam, V = np.linalg.eig(a)

In [34]:
V[:,0] * Lam[0] == a @ V[:,0]

array([ True, False])

In [35]:
V[:,0] * Lam[0] , a @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [36]:
np.allclose(V[:0] * Lam[0], a @ V[:,0])

True

In [37]:
np.allclose(V @ np.diag(Lam), a @ V)

True